[package]
name = "hetseq"
version = "0.1.1"
authors = ["omni-viral"]
description = "Defines traits and types to work with heterogenous sequences"
license = "Apache-2.0/MIT"
repository = "https://github.com/omni-viral/hetseq"

[features]
nightly = []